<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container10Q45aZ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container10Q45aZ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container10Q45aZ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container10Q45aZ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container10Q45aZ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '10Q45aZ',
    'container.build_id' => '4002852b',
    'container.build_time' => 1554990362,
], __DIR__.\DIRECTORY_SEPARATOR.'Container10Q45aZ');
